### ISSUE TITLE
Add Zookie functionality to Delphinius

### ISSUE THREAD

**Issue by Hellblazer** [salesforce/apollo#153]
Use the [block height of the SQL state](https://github.com/salesforce/apollo/blob/64a835921d8e69c78832b31f6cfe7dd2e9b728e6/sql-state/src/main/java/com/salesforce/apollo/state/SqlStateMachine.java#L463) as the Zookie equivalent for Delphinius.  This provides the same "happened before" semantics that the Atomic clock (and additional time protocols) ensure.

**Comment by sfdc-hhildebrand** [comment]
Closed with #216
